Repository DeveloperAcademy-POSTECH/MacC_Team_Beartear, pull requests merged in 2022-11, with the labels that each got.

#32 Feat: Add Utility code to share
  Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
  Gom4ziz/Gom4ziz/Presenter/ShareTest/ShareTestView.swift
  Gom4ziz/Gom4ziz/Presenter/ShareTest/ShareTestViewController.swift
  Gom4ziz/Gom4ziz/Utility/AutoLayoutUIView.swift
  Gom4ziz/Gom4ziz/Utility/Loadable.swift
  Gom4ziz/Gom4ziz/Utility/RxViewController.swift
Labels: feature, 머지하세요

#54 Feat: Artwork를 DB에서 불러올 수 있는 repository를 구현했습니다
  Gom4ziz/Source/Data/FirebaseArtworkRepository.swift
Labels: feature, 머지하세요

#59 Feat: #46 ArtworkReview를 DB에서 불러오는 기능을 구현했습니다.
  Gom4ziz/Source/Data/Repository/FirebaseArtworkReviewRepository.swift
Labels: feature, 간단하니까 빨리 리뷰좀

#64 62 [Feature] 질문 답변 작성 화면 진입 시, 자동으로 키보드가 올라오도록 구현한다.
  Gom4ziz/Source/Domain/Model/MockData.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerViewController.swift
Labels: feature, 머지하세요

#82 FirebaseArtworkRepository.swift~develop 파일 제거
  Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift~develop
Labels: 간단하니까 빨리 리뷰좀

#81 FirebaseArtworkRepository.swift~Style: Remove unnecessary argu… 파일 제거
  Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift~Style: Remove unnecessary argument on fetchArtworkDescription
Labels: 간단하니까 빨리 리뷰좀

#78 [Feature] #74 UserRepository에 DB에서 User를 불러오는 FetchUser() 함수 추가
  Gom4ziz/Source/Data/Repository/FirebaseUserRepository.swift
Labels: feature, 리버, 간단하니까 빨리 리뷰좀

#72 [Feature] #55 Domain 영역에서 Artwork를 불러오는 로직을 추가하였습니다
  Gom4ziz/Source/Domain/Model/Artwork.swift
  Gom4ziz/Source/Domain/RequestNextArtworkUsecase.swift
  Gom4ziz/Source/Presenter/QuestionViewModel.swift
  Gom4ziz/Source/Presenter/WeeklyArtworkStatus.swift
Labels: feature, 호종이, 재리뷰 필요

#87 [Feature] #80: DB에서 Review된 ArtworkList를 불러온다
  Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
  Gom4ziz/Source/Domain/UseCase/FetchReviewedArtworkUsecase.swift
  Gom4ziz/Source/Extension/RxSwift+Firestore.swift
Labels: feature, 리버, 재리뷰 필요

#89 [Feature]: 하이라이트 칠 수 있는 텍스트뷰를 구현했습니다.
  Gom4ziz/Resource/Assets.xcassets/Highlight.colorset/Contents.json
  Gom4ziz/Source/Domain/Model/Highlight.swift
  Gom4ziz/Source/Domain/Model/HighlightsProcessor.swift
  Gom4ziz/Source/Domain/Model/MockData.swift
  Gom4ziz/Source/Extension/Array.swift
  Gom4ziz/Source/Extension/Color.swift
  Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
  Gom4zizTests/Source/HighlightsProcessorTests.swift
Labels: feature, 코드 리뷰 빨리 급함

#93 HTTP 요청을 통해 이미지를 비동기적으로 불러오는 AsyncImageView를 추가했습니다.
  .swiftlint.yml
  Gom4ziz/Source/Extension/UIImageView.swift
  Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
  Gom4ziz/Source/Utility/ImageCacheManager.swift
Labels: feature

#100 refact: #99 hifi에 따른 entity가 변경되었습니다. (questionAnswer 추가, timeStamp 타입 Date -> Int)
  Gom4ziz/Source/Domain/Model/ArtworkReview.swift
  Gom4ziz/Source/Domain/Model/MockData.swift
  Gom4ziz/Source/Domain/Model/QuestionAnswer.swift
Labels: refactor, 리버, 코드 리뷰 빨리 급함, 간단하니까 빨리 리뷰좀

#108 [Feature] #105 리버와 함께 사용할 MainViewController와 MainView를 충돌을 피하기 위해서 미리 만들었습니다
  Gom4ziz/Source/Presenter/Main/MainView.swift
  Gom4ziz/Source/Presenter/Main/MainViewController.swift
Labels: feature, 간단하니까 빨리 리뷰좀

#116 앱, 테스트 타겟만 린트할 수 있도록 린트 파일을 수정했습니다!
  .swiftlint.yml
Labels: docs, 간단하니까 빨리 리뷰좀

#114 [Feature] #47 sceneDelegate 설정, 온보딩에 필요한 component, viewController, view 파일 추가
  Gom4ziz/Source/Domain/Model/Error.swift
  Gom4ziz/Source/Presenter/Component/OnBoardingButton.swift
  Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
  Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstView.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstViewController.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingPageViewController.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingSecond/OnBoardingSecondView.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingSecond/OnBoardingSecondViewController.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingThird/OnBoardingThirdView.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingThird/OnBoardingThirdViewController.swift
  Gom4ziz/Source/Presenter/OnBoarding/OnBoardingViewController.swift
  Gom4ziz/Source/Presenter/WeeklyArtworkStatus.swift
  Gom4ziz/Source/System/SceneDelegate.swift
Labels: feature, 머지하세요

#122 [Refactor] #113: HighlightTextView를 MyFeedView에 추가하여 리팩토링했습니다.
  Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
  Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
  Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
Labels: refactor, 에코, 머지하세요

#145 로티 라이브러리를 추가했습니다.
  Project.swift
Labels: chore, 간단하니까 빨리 리뷰좀
