Repository DeveloperAcademy-POSTECH/MacC_Team_Beartear, pull requests merged in 2022-12, with the labels that each got.

#152 Highlighted Text View 에 rx extension 을 추가하고, QuestionAnswerViewModel의 relay에 바인딩했습니다.
  .swiftlint.yml
  Gom4ziz/Source/Extension/HighlightedTextView+RxRelay.swift
  Gom4ziz/Source/Extension/UITextView+TextStyle.swift
  Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionModal.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionView.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionViewController.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewModel.swift
  Gom4ziz/Source/Utility/UIViewTestHelper.swift
Labels: feature, 코드 리뷰 빨리 급함

#161 Refactor: Fix QuestionAnswerView to show error view when failed to load
  Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionViewController.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerView.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewController.swift
  Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewModel.swift
  Gom4ziz/Source/System/SceneDelegate.swift
Labels: refactor, 간단하니까 빨리 리뷰좀

#164 Toast UI를 구현하고, 쉽게 사용할 수 있도록 extension을 추가했습니다.
  Gom4ziz/Source/Extension/UIViewController+ErrorAlert.swift
  Gom4ziz/Source/Extension/UIViewController+Toast.swift
  Gom4ziz/Source/Presenter/Component/ToastView.swift
  Gom4ziz/Source/System/SceneDelegate.swift
  Gom4ziz/Source/Utility/UIViewTestHelper.swift
Labels: feature, 간단하니까 빨리 리뷰좀, 머지하세요

#181 refac: ReviewedArtworkCell에서 사용되는 AsyncImageView 이미지 변경 가능하게 수정
  Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/ReviewedArtworkCell.swift
Labels: refactor, 간단하니까 빨리 리뷰좀

#182 [Feat]: reviewdArtworkCellList를load할 때 fail시 error처리
  Gom4ziz/Source/Constants/ErrorViewMessage.swift
  Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/MainViewController.swift
Labels: feature, 간단하니까 빨리 리뷰좀

#189 [Hotfix] 네비게이션바에 mainViewController가 가려지는 문제 해결
  Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/MainViewController.swift
Labels: fix, 코드 리뷰 빨리 급함, 간단하니까 빨리 리뷰좀

#195 [Fix] : 번들ID 변경으로 인한 파이어베이스 infoPlist 추가 및 UI 버그를 수정했습니다.
  Gom4ziz/Resource/GoogleService-Info.plist
  Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
  Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
Labels: fix, 코드 리뷰 빨리 급함, 간단하니까 빨리 리뷰좀

#197 [Feature] 질문 이미지 프레임 추가
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask0.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask0.imageset/QuestionImageMask8.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask1.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask1.imageset/MainFrame.svg
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask2.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask2.imageset/QuestionImageMask2.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask3.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask3.imageset/QuestionImageMask3.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask4.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask4.imageset/QuestionImageMask4.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask5.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask5.imageset/QuestionImageMask5.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask6.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask6.imageset/QuestionImageMask6.png
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask7.imageset/Contents.json
  Gom4ziz/Resource/Assets.xcassets/QuestionImageMask7.imageset/QuestionImageMask7.png
  Gom4ziz/Source/Constants/ImageName.swift
  Gom4ziz/Source/Presenter/Main/WeeklyQuestion/MainQuestionView.swift
Labels: fix
